name: pizza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  bloc:
  flutter_bloc:
  equatable:
  cupertino_icons:

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  andriod: true
  ios: true
  image_path_android: "assets/icon/pizza.png"
  image_path_ios: "assets/icon/pizza.png"
  adaptive_icon_background: "assets/icon/pizza.png"
  adaptive_icon_foreground: "assets/icon/pizza.png"
  adaptive_icon_monochrome: "assets/icon/pizza.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
